spring:
  datasource:

    url: jdbc:mysql://localhost:3306/basicboard?serverTimezone=UTC&characterEncoding=UTF-8
    username: yoontiger
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


  messages:
    basename: messages, errors


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace



mybatis:
  mapper-locations: classpath:mapper/*.xml

  config-location: classpath:config/mybatis-config.xml








